syntax = "proto3";
package judge;

option go_package = ".;judge";

service JudgeService  {
  rpc Judge (JudgeRequest) returns (JudgeResponse) {}
}

message CaseResult {
  bool passed = 1;   // 是否通过
  int64 time = 2;    // 本组耗时
  int64 memory = 3;  // 本组内存
  string status = 4; // 当前测试用例状态
  string output = 5; // 用户程序输出
}

message TestCase {
  string input = 1;
  string output = 2;
}

message JudgeRequest {
  string code = 1; // 用户代码
  int32 codeType = 2; // 用户代码类型
  int64 cpuLimit = 3; // CPU限制
  int64 memoLimit = 4; // 内存限制
  repeated TestCase testCases = 5; // 测试用例
}

message JudgeResponse {
  string status = 1; // 状态 AC/WA/TLE/MLE
  string stdout = 2; // 标准输出
  string stderr = 3; // 标准错误
  int64 time = 4; // 实际运行时间(ns)
  int64 memory = 5; // 实际使用内存
  repeated CaseResult results = 6; // 测试结果
}

//protoc --go_out=. --go_opt=paths=source_relative \
//--go-grpc_out=. --go-grpc_opt=paths=source_relative \
//judge.proto