// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: execute.proto

package execute

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodeType      int32                  `protobuf:"varint,1,opt,name=codeType,proto3" json:"codeType,omitempty"`   // 用户代码类型
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`            // 用户代码
	CpuLimit      int64                  `protobuf:"varint,3,opt,name=cpuLimit,proto3" json:"cpuLimit,omitempty"`   // CPU限制
	MemoLimit     int64                  `protobuf:"varint,4,opt,name=memoLimit,proto3" json:"memoLimit,omitempty"` // 内存限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_execute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_execute_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetCodeType() int32 {
	if x != nil {
		return x.CodeType
	}
	return 0
}

func (x *ExecuteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteRequest) GetCpuLimit() int64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *ExecuteRequest) GetMemoLimit() int64 {
	if x != nil {
		return x.MemoLimit
	}
	return 0
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`  // 状态
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`  // 标准输出
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`  // 标准错误
	Time          int64                  `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`     // 实际运行时间
	Memory        int64                  `protobuf:"varint,5,opt,name=memory,proto3" json:"memory,omitempty"` // 实际使用内存
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_execute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_execute_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteResponse) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *ExecuteResponse) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

var File_execute_proto protoreflect.FileDescriptor

const file_execute_proto_rawDesc = "" +
	"\n" +
	"\rexecute.proto\x12\rcompileandrun\"z\n" +
	"\x0eExecuteRequest\x12\x1a\n" +
	"\bcodeType\x18\x01 \x01(\x05R\bcodeType\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\bcpuLimit\x18\x03 \x01(\x03R\bcpuLimit\x12\x1c\n" +
	"\tmemoLimit\x18\x04 \x01(\x03R\tmemoLimit\"\x85\x01\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x03R\x04time\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\x03R\x06memory2_\n" +
	"\rCompileAndRun\x12N\n" +
	"\vExecuteCode\x12\x1d.compileandrun.ExecuteRequest\x1a\x1e.compileandrun.ExecuteResponse\"\x00B\vZ\t.;executeb\x06proto3"

var (
	file_execute_proto_rawDescOnce sync.Once
	file_execute_proto_rawDescData []byte
)

func file_execute_proto_rawDescGZIP() []byte {
	file_execute_proto_rawDescOnce.Do(func() {
		file_execute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_execute_proto_rawDesc), len(file_execute_proto_rawDesc)))
	})
	return file_execute_proto_rawDescData
}

var file_execute_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_execute_proto_goTypes = []any{
	(*ExecuteRequest)(nil),  // 0: compileandrun.ExecuteRequest
	(*ExecuteResponse)(nil), // 1: compileandrun.ExecuteResponse
}
var file_execute_proto_depIdxs = []int32{
	0, // 0: compileandrun.CompileAndRun.ExecuteCode:input_type -> compileandrun.ExecuteRequest
	1, // 1: compileandrun.CompileAndRun.ExecuteCode:output_type -> compileandrun.ExecuteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_execute_proto_init() }
func file_execute_proto_init() {
	if File_execute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_execute_proto_rawDesc), len(file_execute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_execute_proto_goTypes,
		DependencyIndexes: file_execute_proto_depIdxs,
		MessageInfos:      file_execute_proto_msgTypes,
	}.Build()
	File_execute_proto = out.File
	file_execute_proto_goTypes = nil
	file_execute_proto_depIdxs = nil
}
